# Generated by Django 5.1.3 on 2024-11-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0006_alter_dailylog_check_in_time_alter_dailylog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remaining_leave_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_custom_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='remaining_leave_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_custom_set', to='auth.permission'),
        ),
    ]
